title: Don Norman Design Award Summit 2025 (DNDA25)
url: https://www.dnda25.com.sg
favicon: /images/images.jpg
colors:
  primary-color: "#f5a623"
  secondary-color: "#c66924"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#50b198"
    - title: media-color-three
      color: "#dd8e1c"
    - title: media-color-four
      color: "#696969"
    - title: media-color-five
      color: "#000000"
description: The DNDA25 Summit (19–21 Nov 2025, Singapore) brings together
  changemakers in design, education, business and community for three days of
  purposeful dialogue, creative exploration and humanity‑centred action. Join us
  as education meets innovation to inspire sustainable solutions for global
  impact.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.di88sw0txp6r7.amplifyapp.com
prod: https://master.d25fsp3cskqtf7.amplifyapp.com
facebook-pixel: ""
resources_name: dnda25
shareicon: /images/images.jpg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
