title: Don Norman Design Award Summit 2025 (DNDA25)
url: https://dnda25.sp.edu.sg
favicon: /images/dndsummit_logo_750x750_300dpi.png
colors:
  primary-color: "#f5a623"
  secondary-color: "#c66924"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#50b198"
    - title: media-color-three
      color: "#dd8e1c"
    - title: media-color-four
      color: "#696969"
    - title: media-color-five
      color: "#000000"
description: The Don Norman Design Award (DNDA) organisation is dedicated to
  promoting the global adoption of Humanity-Centred Design (HCD+). DNDA
  champions holistic and sustainable design practices that benefit both society
  and the planet. Through its annual flagship events, the DNDA Awards Program
  and Summit, DNDA celebrates groups making significant societal contributions,
  rallies leaders to embrace an HCD+ approach to innovation, and nurtures the
  development of emerging designers and educators. Founded in 2023 as a U.S.
  based nonprofit organisation, DNDA draws inspiration from the work of Don
  Norman, a luminary in the world of design with a distinguished career as an
  author, teacher, founder, advisor, and executive at renowned companies such as
  Apple and HP.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.di88sw0txp6r7.amplifyapp.com
prod: https://master.d25fsp3cskqtf7.amplifyapp.com
facebook-pixel: ""
resources_name: dnda25
shareicon: /images/DNDA25_SP_logo_bk.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
